### ISSUE TITLE
psycopg2.error "ENTRY.type does not exist"

### ISSUE THREAD

**Issue by WaldoPepper** [adrianschlatter/ppf.jabref#5]
Hi,

I am testing in a Conda environment with:

```
greenlet          3.0.3
pip               24.2
ppf-jabref        0.1.0
psycopg2          2.9.9
setuptools        72.1.0
SQLAlchemy        2.0.34
typing_extensions 4.12.2
wheel             0.43.0
```

With `JabRef 5.15` on `PostgreSQL 15.1` I get a strange error when trying out the example code (I cut the output down to the part I think is relevant):

```
Traceback (most recent call last):
  File "C:\Users\glaes\.conda\envs\jabref_python_3.9\lib\site-packages\sqlalchemy\engine\base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "C:\Users\glaes\.conda\envs\jabref_python_3.9\lib\site-packages\sqlalchemy\engine\default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column ENTRY.type does not exist
LINE 1: SELECT "ENTRY"."SHARED_ID" AS "ENTRY_SHARED_ID", "ENTRY".typ...
```

At first I thought it was the schema search path but I think I can rule that out now....

Any suggestions?

**Comment by WaldoPepper** [comment]
....ok, looks like I found something: there seems to base a case-sensitivity with regard to the column names.

In my database the column names a all caps:

![image](https://github.com/user-attachments/assets/ea1abf66-2c02-4b31-90d3-1bd33b3ab4cc)

When I rename e.g. column name `TYPE` to `type`, I get an error on the `VERSION` column....
